### ISSUE TITLE
Question: working with non-public schema

### ISSUE THREAD

**Issue by jfavrod** [paulelie/winston-pg-native#5]
I created the table for the `winston-pg-notive` to push to in a schema named `logs`. The tableName is `winston`, example below:

```sql
CREATE SCHEMA logs;

CREATE TABLE logs.winston (
  timestamp timestamp without time zone DEFAULT now(),
  level character varying,
  message character varying,
  meta json
);
```

When configured to work with this table, I receive the following error:

```
(node:93692) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Error: relation "logs.winston" does not exist\n    at module.exports.Client._emitResult (/Users/jfavr1/dev/labor-calendar/service/node_modules/pg-native/index.js:173:26)\n    at module.exports.Client._read (/Users/jfavr1/dev/labor-calendar/service/node_modules/pg-native/index.js:215:31)\n    at PQ.emit (events.js:198:13)')
... logging output omitted ...
```

I created a new table in the public schema called `logs` with the same description of the `logs.winston` table. I updated the configuration to use the `logs` table, and it worked.

Can PostgreSQL Transport class be configured to work with schemas besides public?

**Comment by danilomourelle** [comment]
Have you tried to set the schema to connection string?

Like `postgresql://<user>:<pass>@localhost:5432/<database>?schema=logs`
